@table = category
@id = 1
@body = {"with": [ "product" ]}

GET http://maboutique.api/init

###

GET http://maboutique.api/{{table}}

###
GET http://maboutique.api/{{table}}/{{id}}

###
POST http://maboutique.api/{{table}}
Content-Type: application/json

{{body}}

###
PUT http://maboutique.api/{{table}}/{{id}}
Content-Type: application/json

{{body}}

###
PATCH http://maboutique.api/{{table}}/{{id}}

###
DELETE http://maboutique.api/{{table}}/{{id}}

###
POST http://maboutique.api/{{table}}/0
Content-Type: application/json

{{body}}

###
POST http://maboutique.api/{{table}}/{{id}}
Content-Type: application/json

{{body}}

### specific ThemeDetail

GET http://maboutique.api/themeDetail/{{id}}