@table = category
@id = 1
@body = {"title": "écologie", "img_src": "https://picsum.photos/id/237/200/300"}

GET http://maboutique.api/init

###

GET http://maboutique.api/{{table}}

###
GET http://maboutique.api/{{table}}/{{id}}

###
POST http://maboutique.api/{{table}}
Content-Type: application/json

{{body}}

###
PUT http://maboutique.api/{{table}}/{{id}}
Content-Type: application/json

{{body}}

###
PATCH http://maboutique.api/{{table}}/{{id}}

###
DELETE http://maboutique.api/{{table}}/{{id}}
